"""Rewrite historical `fund_label` values to the fund group.

Runs made before this change recorded the data-file label in `fund_label`, so a
ticker's history slices (`AAPL`, `AAPL-3Y`, `AAPL-4Y`) looked like three separate
funds to every consumer that groups by that column -- the dashboard, the top-5
parameter summary, compare_presets.py, suggest_next_runs.py.

backtest_stocks.py now records the group (`AAPL`) in `fund_label` and keeps the
slice in a new `fund_slice_label` column. This one-off script brings existing
history into line:

  * `fund_slice_label` is added (next to `fund_label`) holding the current value,
    so nothing is lost -- run_grid.ps1's resume key reads it.
  * `fund_label` becomes `fund_group_from_label(fund_label)`.
  * Per-slice `<SLICE>-top5_parameter_sets.csv` files are deleted; the group file
    is regenerated by refresh_top5_parameter_sets() on the next run.

Files are copied into outputs/_backfill_backup_<timestamp>/ before being written,
and every read/write takes the same cross-process lock the backtester uses, so
this is safe to run while a backtest is appending.

Usage:
    python backfill_fund_label.py                 # dry run: report what would change
    python backfill_fund_label.py --apply         # perform the rewrite
    python backfill_fund_label.py --slices AAPL-3Y AAPL-4Y   # limit to these labels
"""

import argparse
import re
import shutil
from datetime import datetime
from pathlib import Path

import pandas as pd

from common import OUTPUTS_DIR, file_lock, fund_group_from_label

TUNINGS_DIR = OUTPUTS_DIR / "tunings"
FUNDS_DIR = OUTPUTS_DIR / "funds"

# Cumulative history files, matched by exact name only. Hand-made snapshots that
# merely start with the same stem ("backtest_run_history - 20260724.csv",
# "backtest_tuning_history.bak_....csv") are archives and must be left untouched.
SHARED_STEMS = (
    "backtest_run_history",
    "backtest_window_history",
    "backtest_tuning_history",
    "top5_parameter_sets_by_fund",
)

# Lock-fallback copies written by build_lock_fallback_path() hold real rows that
# were never merged back, so they are regrouped too.
LOCK_FALLBACK = re.compile(
    r"^(" + "|".join(SHARED_STEMS) + r")_\d{8}_\d{6}_\d+\.csv$"
)

# Per-fund files. Anything else in a tunings/ folder (manual "- Copy" duplicates,
# spreadsheets) is left alone rather than guessed at.
FUND_SUFFIXES = (
    "-backtest_run_history.csv",
    "-backtest_window_history.csv",
    "-backtest_tuning_history.csv",
    "-top5_parameter_sets.csv",
)

TOP5_SUFFIX = "-top5_parameter_sets.csv"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Rewrite historical fund_label values to the fund group.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--apply", action="store_true",
                        help="Actually write. Without this the script only reports.")
    parser.add_argument("--slices", nargs="+", default=None,
                        help="Only rewrite rows whose current fund_label is one of these "
                             "(default: every label carrying a -NY suffix).")
    parser.add_argument("--keep-slice-top5", action="store_true",
                        help="Keep the superseded per-slice *-top5_parameter_sets.csv files.")
    return parser.parse_args()


def discover_history_files(skip=()):
    """Every history CSV whose fund_label column this script understands."""
    skip = set(skip)
    found = []
    if TUNINGS_DIR.is_dir():
        for path in sorted(TUNINGS_DIR.glob("*.csv")):
            canonical = path.stem in SHARED_STEMS or LOCK_FALLBACK.match(path.name)
            if canonical and path not in skip:
                found.append(path)
    if FUNDS_DIR.is_dir():
        for fund_dir in sorted(FUNDS_DIR.iterdir()):
            # _legacy_backup_* folders are snapshots; leave them as they were.
            if not fund_dir.is_dir() or fund_dir.name.startswith("_"):
                continue
            tunings = fund_dir / "tunings"
            if not tunings.is_dir():
                continue
            for path in sorted(tunings.glob("*.csv")):
                if path.name.endswith(FUND_SUFFIXES) and path not in skip:
                    found.append(path)
    return found


def plan_file(path, only_labels=None):
    """Return (dataframe, changed_row_count, note) for one history file.

    dataframe is None when there is nothing to write.
    """
    try:
        with file_lock(path):
            df = pd.read_csv(path, low_memory=False)
    except pd.errors.EmptyDataError:
        return None, 0, "empty file"

    if "fund_label" not in df.columns:
        return None, 0, "no fund_label column"
    if df.empty:
        return None, 0, "no rows"

    labels = df["fund_label"].astype(str)
    groups = labels.map(fund_group_from_label)
    targets = labels.ne(groups)
    if only_labels is not None:
        targets &= labels.isin(only_labels)

    needs_column = "fund_slice_label" not in df.columns
    changed = int(targets.sum())
    if changed == 0 and not needs_column:
        return None, 0, f"{len(df)} row(s) already grouped"

    if needs_column:
        # Seed the whole column from the pre-rewrite labels: rows that were already
        # group-labelled have themselves as their slice, which is correct.
        df.insert(df.columns.get_loc("fund_label") + 1, "fund_slice_label", labels)
    else:
        missing = df["fund_slice_label"].isna() | df["fund_slice_label"].astype(str).str.strip().eq("")
        df.loc[missing, "fund_slice_label"] = labels[missing]

    df.loc[targets, "fund_label"] = groups[targets]

    note = f"{changed} of {len(df)} row(s) regrouped"
    if needs_column:
        note += "; adding fund_slice_label column"
    return df, changed, note


def stale_top5_files(only_labels=None):
    """Per-slice top-5 files superseded by the group file, which is regenerated."""
    stale = []
    if not FUNDS_DIR.is_dir():
        return stale
    for fund_dir in sorted(FUNDS_DIR.iterdir()):
        if not fund_dir.is_dir() or fund_dir.name.startswith("_"):
            continue
        for path in sorted((fund_dir / "tunings").glob(f"*{TOP5_SUFFIX}")):
            label = path.name[: -len(TOP5_SUFFIX)]
            if fund_group_from_label(label) == label:
                continue  # this is the group's own file
            if only_labels is not None and label not in only_labels:
                continue
            stale.append(path)
    return stale


def backup(path, backup_root):
    destination = backup_root / path.relative_to(OUTPUTS_DIR)
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, destination)
    return destination


def main():
    args = parse_args()
    only_labels = set(args.slices) if args.slices else None
    # Resolved first so files queued for deletion are never also rewritten.
    stale = [] if args.keep_slice_top5 else stale_top5_files(only_labels)
    files = discover_history_files(skip=stale)
    if not files and not stale:
        print(f"No history CSVs found under {OUTPUTS_DIR}. Nothing to do.")
        return 0

    mode = "APPLY" if args.apply else "DRY RUN"
    print(f"[{mode}] scanning {len(files)} history file(s) under {OUTPUTS_DIR}\n")

    planned = []
    for path in files:
        df, changed, note = plan_file(path, only_labels)
        print(f"  {path.relative_to(OUTPUTS_DIR)}\n      {note}")
        if df is not None:
            planned.append((path, df, changed))

    if stale:
        print("\n  superseded per-slice top-5 files (regenerated by the next run):")
        for path in stale:
            print(f"      {path.relative_to(OUTPUTS_DIR)}")

    total = sum(changed for _, _, changed in planned)
    if not args.apply:
        print(f"\nWould rewrite {total} row(s) across {len(planned)} file(s) "
              f"and delete {len(stale)} superseded file(s). Re-run with --apply.")
        return 0

    if not planned and not stale:
        print("\nNothing to write.")
        return 0

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_root = OUTPUTS_DIR / f"_backfill_backup_{timestamp}"
    print(f"\nBacking up originals to {backup_root}")

    for path, df, changed in planned:
        backup(path, backup_root)
        with file_lock(path):
            df.to_csv(path, index=False)
        print(f"  rewrote {changed} row(s): {path.relative_to(OUTPUTS_DIR)}")

    for path in stale:
        backup(path, backup_root)
        path.unlink()
        print(f"  deleted: {path.relative_to(OUTPUTS_DIR)}")

    print(f"\nDone. {total} row(s) regrouped; originals kept in {backup_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
